# Generated by Django 5.1.1 on 2024-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_alter_suppliernode_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliernode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
